### ISSUE TITLE
Right-click context menu not available in Chrome 

### ISSUE THREAD

**Issue by myitcv** [chitsaou/copy-as-markdown#65]
## Summary

Right click context menu not available in latest version of Chrome

## Reproduction Steps

* Select some text on a page
* Right click on the selection to use right-click context menue

## Expected Behavior

Right-click context menu is show

## Actual Behavior

Right-click context menu not available in menu

## Reproducible Environment

- Browser (Version): Google Chrome Version 72.0.3590.0 (Official Build) dev (64-bit)
- Operating System (Version): Mac OS X 10.12.6
- System Language: English
- Example Webpage (if applicable):

<img width="1123" alt="screen shot 2018-10-30 at 11 07 29" src="https://user-images.githubusercontent.com/3374574/47714231-39be8f00-dc34-11e8-9dc1-6a3007a44368.png">

**Comment by chitsaou** [comment]
Thanks for the report. I found there is a race condition in my code. It should be fixed on 2.4.0. Please reopen if you find the same issue again.

**Comment by myitcv** [comment]
Thanks - I'm still not seeing the right click menu option when I select, say, paragraph text. If I right click on an image/link then I do see "Copy as markdown" options, but not if I have selected text and then right click on the selection. This particularly feature is amazing so would be great to have that back!

**Comment by chitsaou** [comment]
Ah, I see your point. No, that feature is not available. The extension only works when you right-click on a link, an image, or an empty area on a page.

**Comment by myitcv** [comment]
Ah my apologies. I must have this mixed up with another plugin
